[versions]
agp = "8.10.1"
annotation = "1.9.1"
bcprovJdk15to18 = "1.80"
spake2Android = "-SNAPSHOT"
junit = "4.13.2"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
bcprov-jdk15to18 = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "bcprovJdk15to18" }
spake2-android = { module = "com.github.Mahmud0808.spake2-java:spake2-android", version.ref = "spake2Android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
